import { Team, User } from './types';

export const mockTeams: Team[] = [
  {
    id: '1',
    name: 'Innovation Squad',
    description: 'Pioneering cutting-edge tech solutions for real-world challenges.',
    leader: 'Sarah Johnson',
    maxMembers: 5,
    currentMembers: 1,
    members: [],
    projectIdea: 'AI-Powered Task Management',
  },
  {
    id: '2',
    name: 'Tech Titans',
    description: 'Driving transformative ideas in blockchain and automation.',
    leader: 'Michael Chen',
    maxMembers: 4,
    currentMembers: 2,
    members: [],
    projectIdea: 'Blockchain Supply Chain',
  },
  {
    id: '3',
    name: 'Digital Dreamers',
    description: 'Envisioning and building immersive digital experiences.',
    leader: 'Emily Rodriguez',
    maxMembers: 5,
    currentMembers: 2,
    members: [],
    projectIdea: 'AR Shopping Experience',
  },
  {
    id: '4',
    name: 'Code Crafters',
    description: 'Meticulously crafting clean and scalable codebases.',
    leader: 'Alex Kim',
    maxMembers: 3,
    currentMembers: 1,
    members: [],
    projectIdea: 'Smart Home Automation',
  },
  {
    id: '5',
    name: 'Data Dynamos',
    description: 'Unlocking insights through data science and machine learning.',
    leader: 'Lisa Wang',
    maxMembers: 5,
    currentMembers: 2,
    members: [],
    projectIdea: 'ML-Based Analytics Platform',
  },
  {
    id: '6',
    name: 'Cloud Chasers',
    description: 'Innovating with scalable and secure cloud-native solutions.',
    leader: 'Ravi Patel',
    maxMembers: 4,
    currentMembers: 2,
    members: [],
    projectIdea: 'Multi-Cloud Deployment Tool',
  },
  {
    id: '7',
    name: 'Pixel Pioneers',
    description: 'Designing pixel-perfect UIs for modern web and mobile apps.',
    leader: 'Nina Gomez',
    maxMembers: 4,
    currentMembers: 3,
    members: [],
    projectIdea: 'Design System for SaaS',
  },
  {
    id: '8',
    name: 'Quantum Coders',
    description: 'Exploring futuristic tech like quantum and edge computing.',
    leader: 'Ethan Wright',
    maxMembers: 5,
    currentMembers: 2,
    members: [],
    projectIdea: 'Edge-Powered IoT System',
  },
  {
    id: '9',
    name: 'Bug Smashers',
    description: 'Dedicated to quality assurance and seamless deployments.',
    leader: 'Amira Singh',
    maxMembers: 3,
    currentMembers: 2,
    members: [],
    projectIdea: 'Automated Testing Pipeline',
  },
  {
    id: '10',
    name: 'Neural Ninjas',
    description: 'Focusing on deep learning, NLP, and AI-based applications.',
    leader: 'Carlos Rivera',
    maxMembers: 5,
    currentMembers: 4,
    members: [],
    projectIdea: 'Real-Time Language Translator',
  },
];

export const mockUser: User = {
  id: '1',
  firstName: 'John',
  lastName: 'Doe',
  email: 'john.doe@example.com',
  role: 'Senior Software Engineer',
  location: 'New York, USA',
  memberSince: '2023-01-01',
  avatar: '',
  skills: ['React', 'TypeScript', 'Node.js', 'Python', 'AWS'],
  socials: {
    github: 'github.com/johndoe',
    linkedin: 'linkedin.com/in/johndoe',
    twitter: 'twitter.com/johndoe_dev',
  },
};
